name: Coverage Test
run-name: Testing the Package
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: yarn

            - name: Run coverage tests
              run: yarn test

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
