name: Coverage and Publish

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Run Tests and Coverage
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: yarn

            - name: Run coverage tests
              run: yarn test

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}

    check-version:
        name: Check if version changed
        runs-on: ubuntu-latest
        needs: test
        outputs:
            changed: ${{ steps.version_check.outputs.changed }}
        steps:
            - name: Check out with history
              uses: actions/checkout@v4
              with:
                  fetch-depth: 2

            - name: Get current package version
              id: current
              run: |
                  echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

            - name: Get previous version from last commit
              id: previous
              run: |
                  git show HEAD^:package.json > prev_package.json
                  echo "version=$(jq -r .version prev_package.json)" >> $GITHUB_OUTPUT

            - name: Compare versions
              id: version_check
              run: |
                  if [ "${{ steps.current.outputs.version }}" != "${{ steps.previous.outputs.version }}" ]; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

    publish:
        name: Publish to NPM
        runs-on: ubuntu-latest
        needs: [test, check-version]
        if: needs.check-version.outputs.changed == 'true'
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: "https://registry.npmjs.org"

            - name: Install dependencies
              run: yarn

            - name: Build package
              run: yarn build

            - name: Publish to NPM
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
